package org.sqlpal.query

import org.sqlpal.*
import java.sql.Connection
import java.sql.SQLException
import java.sql.Statement
import kotlin.reflect.KClass
import kotlin.reflect.full.hasAnnotation
import kotlin.reflect.full.memberProperties

//////////////////////////////////////////////////////////////////////////////////
//--------------------- Contains methods to perform INSERT ---------------------//
//////////////////////////////////////////////////////////////////////////////////

/** Inserts specified [entity] into the table, considering that:
 * - the table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - the columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option.
 * Properties annotated with [AutoGen] are not included in the INSERT statement,
 * but are read from the INSERT results if [updateAutoGenValues] is true (the default).
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when you need to execute in a transaction, use [transaction] method for convenience.
 * @param updateAutoGenValues true (the default) to update properties with values of autogenerated columns (e.g. ID).
 * Only values of properties annotated with [AutoGen] are updated.
 * @return number of inserted rows. */
fun insert(entity: Any, con: Connection? = null, updateAutoGenValues: Boolean = true) =
    execInsertOrUpdate(entity, null, con, updateAutoGenValues,
        "INSERT INTO %s (", "") { _, sb, params -> appendValuesClause(sb, params.size) }

/** Tries to update specified [entity] in the table, and if not succeeded, inserts it, considering that:
 * - the table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - the columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - the property that maps to the primary key column is annotated with [Id].
 *
 * Guarantees safe concurrent inserts/updates of the row with the same key from multiple connections.
 * Limitation: assumes rows for a given key are not deleted concurrently with upsert.
 * If deletion occurs between the insert attempt and the update, the method may throw instead of persisting the row;
 * this is intentional, since a simultaneous upsert and delete of the same key have no defined winner.
 *
 * Properties annotated with [AutoGen] are not included in the INSERT statement, but are read from INSERT results.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when you need to execute in a transaction, use [transaction] method for convenience.
 * @param insertFirst Performance hint. Set to true if inserts are more often. Otherwise, it will try to update first.
 * @return number of inserted or updated rows. */
inline fun <reified T: Any> upsert(entity: T, con: Connection? = null, insertFirst: Boolean = false): Int {
    var affectedCount = // General logic - try to update > if failed try to insert > if failed try to update again:
        if (insertFirst) 0 else update(entity, con) // 1. First try to update as it's cheaper than insert with savepoint
    if (affectedCount == 0) {                       // 2. if nothing was updated,
        // On Postgres if autoCommit is off, then failed insert breaks the transaction, so add savepoint to avoid it
        val sp = if (con?.autoCommit == false) con.setSavepoint() else null
        try {
            affectedCount = insert(entity, con)     // 3. then try to insert it,
        }
        catch (e: SQLException) {                   // 4. if insert threw an exception,
            sp?.let { con?.rollback(it) }
            affectedCount = update(entity, con)     // 5. try to update again as row might be inserted by other connection
            if (affectedCount == 0) throw e         // 6. if nothing updated, then exception is not our logic related, just rethrow
        }
        sp?.let { con?.releaseSavepoint(it) }
    }
    return affectedCount
}

/** Inserts multiple items in a single batch, considering:
 * - all items are of the same type,
 * - the table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - the columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option.
 * @param items any iterable source of items to insert.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when you need to execute in a transaction, use [transaction] method for convenience.
 * @return number of inserted rows. */
inline fun <reified T: Any> insertMany(items: Iterable<T>, con: Connection? = null) =
    // Public inline function can't access private members, while it must be inline to get generic type.
    // So implementation is moved to separate internal method, that receives type just as parameter.
    insertMany(T::class, items, con)

@PublishedApi
internal fun <T: Any> insertMany(itemClass: KClass<T>, items: Iterable<T>, con: Connection? = null): Int
{
    val tableName = entityName(itemClass)
    val sb = StringBuilder("INSERT INTO $tableName (")

    val props = itemClass.memberProperties.filter { !it.hasAnnotation<SqlIgnore>() && !it.hasAnnotation<AutoGen>() }

    for (p in props)  {
        sb.append(colName(p))
        sb.append(',')
    }
    if (!sb.endsWith(',')) throw SqlPalException("Cannot generate an INSERT statement " +
            "for the class ${itemClass.qualifiedName} because it does not have properties suitable for insertion.")
    sb.deleteCharAt(sb.length - 1) // Remove trailing comma
    appendValuesClause(sb, props.size)

    val insertedCounts = Query(sb.toString(), ArrayList(props.size))
        .doBatch(con, items) { item, params ->
            for (p in props) addPropToBindParams(item, p, params)
        }
    // Driver may report SUCCESS_NO_INFO (-2) instead of the actual count
    // (e.g. Postgres does it when reWriteBatchedInserts is enabled), count such statements as 1 inserted row.
    return insertedCounts.sumOf { if (it == Statement.SUCCESS_NO_INFO) 1 else it }
}

private fun appendValuesClause(sb: StringBuilder, bindParamsCount: Int) {
    sb.append(") VALUES (")
    repeat(bindParamsCount) { sb.append("?,") }
    sb.deleteCharAt(sb.length - 1) // Remove trailing comma
    sb.append(')')
}