package org.sqlpal.query

import org.sqlpal.*
import java.sql.Connection
import kotlin.reflect.KClass
import kotlin.reflect.full.hasAnnotation
import kotlin.reflect.full.memberProperties

//////////////////////////////////////////////////////////////////////////////////
//--------------------- Contains methods to perform INSERT ---------------------//
//////////////////////////////////////////////////////////////////////////////////

/** Inserts specified entity to the table, considering that:
 * - table is named as class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as properties in accordance with [SqlPal.convertNamesToSnakeCase] option.
 * Properties annotated with [AutoGen] are not included into INSERT,
 * but are read from INSERT results if [updateAutoGenValues] is true.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when need to execute in transaction, use [transaction] method for convenience.
 * @param updateAutoGenValues true (the default) to update properties with values of autogenerated columns (e.g. ID).
 * Only values of properties annotated with [AutoGen] are updated.
 * @return number of inserted rows. */
fun insert(entity: Any, con: Connection? = null, updateAutoGenValues: Boolean = true) =
    execInsertOrUpdate(entity, null, con, updateAutoGenValues,
        "INSERT INTO %s (", "") { _, sb, params -> appendValuesClause(sb, params.size) }

/** Inserts multiple items in single batch, considering:
 * - all items are of the same type,
 * - table is named as class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as properties in accordance with [SqlPal.convertNamesToSnakeCase] option.
 * @param items any iterable source of items to insert.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when need to execute in transaction, use [transaction] method for convenience.
 * @return number of inserted rows. */
inline fun <reified T: Any> insertMany(items: Iterable<T>, con: Connection? = null) =
    // Public inline function can't access private members, while it must be inline to get generic type.
    // So implementation is moved to separate internal method, that receives type just as parameter.
    insertMany(T::class, items, con)

@PublishedApi
internal fun <T: Any> insertMany(itemClass: KClass<T>, items: Iterable<T>, con: Connection? = null): Int
{
    val tableName = entityName(itemClass::class)
    val sb = StringBuilder("INSERT INTO $tableName (")

    val props = itemClass.memberProperties.filter { !it.hasAnnotation<SqlIgnore>() && !it.hasAnnotation<AutoGen>() }

    for (p in props)  {
        sb.append(colName(p))
        sb.append(',')
    }
    sb.deleteCharAt(sb.length - 1) // Remove trailing comma
    appendValuesClause(sb, props.size)

    val insertedCounts = Query(sb.toString(), ArrayList(props.size))
        .doBatch(con, items) { item, params ->
            for (p in props) addPropToBindParams(item, p, params)
        }
    return insertedCounts.sum()
}

private fun appendValuesClause(sb: StringBuilder, bindParamsCount: Int) {
    sb.append(") VALUES (")
    repeat(bindParamsCount) { sb.append("?,") }
    sb.deleteCharAt(sb.length - 1) // Remove trailing comma
    sb.append(')')
}