package org.sqlpal.query

import org.sqlpal.*
import java.sql.Connection
import kotlin.reflect.KClass
import kotlin.reflect.KMutableProperty0
import kotlin.reflect.KProperty0
import kotlin.reflect.KProperty1

//////////////////////////////////////////////////////////////////////////////////
//--------------------- Contains internal utility methods ----------------------//
//////////////////////////////////////////////////////////////////////////////////

/** Updates values in the corresponding table from the specified entity, considering that:
 * - table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - if [where] parameter is not specified, then the property that maps to the primary key column must be annotated with [Id].
 * Properties annotated with [AutoGen] are not included in the UPDATE,
 * but are read from UPDATE results if [updateAutoGenValues] is true.
 * @param entity object to update.
 * @param where WHERE clause content specified with -"..." or -"""...""" syntax.
 * After the conditions, any clause that goes after WHERE (e.g. ORDER BY or LIMIT) can be specified.
 * If the parameter is specified, then it's appended to UPDATE command,
 * otherwise table is filtered by value from property annotated with [Id].
 * @param updateAutoGenValues true to update properties with values from autogenerated columns (e.g. ID).
 * Only values of properties annotated with [AutoGen] are updated.
 * @return number of updated rows. */
fun update(entity: Any, where: Query? = null, updateAutoGenValues: Boolean = false) =
    update(entity, null, where, updateAutoGenValues, null)

/** Updates values in the corresponding table from the specified entity, considering that:
 * - table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - if [where] parameter is not specified, then the property that maps to the primary key column must be annotated with [Id].
 * Properties annotated with [AutoGen] are not included in the UPDATE,
 * but are read from UPDATE results if [updateAutoGenValues] is true.
 * @param entity object to update.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when you need to execute in a transaction, use [transaction] method for convenience.
 * @param where WHERE clause content specified with -"..." or -"""...""" syntax.
 * After the conditions, any clause that goes after WHERE (e.g. ORDER BY or LIMIT) can be specified.
 * If the parameter is specified, then it's appended to UPDATE command,
 * otherwise table is filtered by value from property annotated with [Id].
 * @param updateAutoGenValues true to update properties with values from autogenerated columns (e.g. ID).
 * Only values of properties annotated with [AutoGen] are updated.
 * @return number of updated rows. */
fun update(entity: Any, con: Connection? = null, where: Query? = null, updateAutoGenValues: Boolean = false) =
    update(entity, con, where, updateAutoGenValues, null)

/** Updates values in the corresponding table from the specified entity, considering that:
 * - table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - if [where] parameter is not specified, then the property that maps to the primary key column must be annotated with [Id].
 * Properties annotated with [AutoGen] are not included in the UPDATE,
 * but are read from UPDATE results if [updateAutoGenValues] is true.
 * @param entity object to update.
 * @param where WHERE clause content specified with -"..." or -"""...""" syntax.
 * After the conditions, any clause that goes after WHERE (e.g. ORDER BY or LIMIT) can be specified.
 * If the parameter is specified, then it's appended to UPDATE command,
 * otherwise table is filtered by value from property annotated with [Id].
 * @param updateAutoGenValues true to update properties with values from autogenerated columns (e.g. ID).
 * Only values of properties annotated with [AutoGen] are updated.
 * @param propList Provide lambda with call to one of the following functions:
 * - [only] - provides list of properties to update in the database, e.g.:
 *
 * update(person) { only(::name) } - to update only a 'name' column.
 * - [except] - provides list of properties to exclude, while all other properties will be updated in the database, e.g.:
 *
 * update(person) { except(::name, ::city) } - to update all columns except 'name' and 'city'.
 * - [set] - same as [only], but also sets specified properties to specified values before update, e.g.:
 *
 * update(person) { set (::position to "Developer") } - to set value in both 'position' property and column.
 * @return number of updated rows. */
fun <T: Any> update(entity: T, where: Query? = null, updateAutoGenValues: Boolean = false, propList: T.() -> PropsToUpdate) =
    update(entity, null, where, updateAutoGenValues, propList)

/** Updates values in the corresponding table from the specified entity, considering that:
 * - table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - if [where] parameter is not specified, then the property that maps to the primary key column must be annotated with [Id].
 * Properties annotated with [AutoGen] are not included in the UPDATE,
 * but are read from UPDATE results if [updateAutoGenValues] is true.
 * @param entity object to update.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when you need to execute in a transaction, use [transaction] method for convenience.
 * @param where WHERE clause content specified with -"..." or -"""...""" syntax.
 * After the conditions, any clause that goes after WHERE (e.g. ORDER BY or LIMIT) can be specified.
 * If the parameter is specified, then it's appended to UPDATE command,
 * otherwise table is filtered by value from property annotated with [Id].
 * @param updateAutoGenValues true to update properties with values from autogenerated columns (e.g. ID).
 * Only values of properties annotated with [AutoGen] are updated.
 * @param propList Provide lambda with call to one of the following functions:
 * - [only] - provides list of properties to update in the database, e.g.:
 *
 * update(person) { only(::name) } - to update only a 'name' column.
 * - [except] - provides list of properties to exclude, while all other properties will be updated in the database, e.g.:
 *
 * update(person) { except(::name, ::city) } - to update all columns except 'name' and 'city'.
 * - [set] - same as [only], but also sets specified properties to specified values before update, e.g.:
 *
 * update(person) { set (::position to "Developer") } - to set value in both 'position' property and column.
 * @return number of updated rows. */
fun <T: Any> update(entity: T, con: Connection? = null, where: Query? = null, updateAutoGenValues: Boolean = false, propList: (T.() -> PropsToUpdate)?) =
    execInsertOrUpdate(entity, propList?.let { entity.it() }, con, updateAutoGenValues, "UPDATE %s SET ", " = ?",
        if (where == null) ::buildWhereWithId
        else { _, sb, params ->
            sb.append(" WHERE ")
            sb.append(where.sql)
            params.addAll(where.bindParams)
            Unit
        })

/** Is created by [only], [except] and [set] functions to return as the lambda result
 * of the 'propList' parameter of [update] function. Don't use it directly. */
class PropsToUpdate internal constructor(
    val include: Array<out KProperty0<*>>?,
    val exclude: Array<out KProperty0<*>>?
)

/** Provides list of properties to update in the database, see [update] for description. */
fun only(vararg items: KProperty0<*>) = PropsToUpdate(items, null)

/** Provides list of properties to exclude from the update, see [update] for description. */
fun except(vararg items: KProperty0<*>) = PropsToUpdate(null, items)

/** Same as [only], but also sets specified properties to specified values, see [update] for description. */
@Suppress("UNCHECKED_CAST")
fun set(vararg items: Pair<KProperty0<*>, Any?>) = PropsToUpdate(
    Array(items.size) {
        (items[it].first as KMutableProperty0<Any?>).set(items[it].second)
        items[it].first
    }, null)

/** Updates specified columns in the corresponding table, considering that:
 * - table is named as the [entity] class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - the property that maps to the primary key column is annotated with [Id].
 * This overload is useful when  it is necessary to update columns for which there are no corresponding properties in the class.
 * @param entity Entity to update.
 * @param params list of pairs <column name - value to set>.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when need to execute in transaction, use [transaction] method for convenience.
 * @return number of rows affected. */
fun update(entity: Any, params: List<Pair<String, Any?>>, con: Connection? = null): Int {
    if (params.isEmpty()) throw SqlPalException("Cannot generate UPDATE statement " +
            "for the class ${entity::class.qualifiedName} as no columns were passed to the update method.")

    val sb = StringBuilder("UPDATE ${entityName(entity::class)} SET ")

    val bindParams = ArrayList<Any?>(params.size)
    params.forEach {
        sb.append(it.first)
        sb.append(" = ?,")
        bindParams.add(it.second)
    }
    sb.deleteCharAt(sb.length - 1) // Remove trailing comma

    buildWhereWithId(entity, sb, bindParams)
    return exec(Query(sb.toString(), bindParams), con)
}

/** Updates specified columns with specified values in the corresponding table, considering that:
 * - table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option.
 * @param where WHERE clause content specified with -"..." or -"""...""" syntax.
 * After the conditions, any clause that goes after WHERE (e.g. ORDER BY or LIMIT) can be specified.
 * @param propsToSet Pairs of property - value to set,
 * e.g.: Person::position to "Developer", Person::isHired to true.
 * @return number of updated rows. */
inline fun <reified T> updateWhere(where: Query, vararg propsToSet: Pair<KProperty1<T, *>, Any?>) =
    updateWhere(where, null, *propsToSet)

/** Updates specified columns with specified values in the corresponding table, considering that:
 * - table is named as the class in accordance with [SqlPal.convertNamesToSnakeCase] option,
 * - columns are named as the properties in accordance with [SqlPal.convertNamesToSnakeCase] option.
 * @param where WHERE clause content specified with -"..." or -"""...""" syntax.
 * After the conditions, any clause that goes after WHERE (e.g. ORDER BY or LIMIT) can be specified.
 * @param propsToSet Pairs of property - value to set,
 * e.g.: Person::position to "Developer", Person::isHired to true.
 * @param con If specified, then command is executed on it, and it is not closed after use.
 * Otherwise, connection is obtained from pool and released after use.
 * Specifying connection is useful when you need to execute in a transaction, use [transaction] method for convenience.
 * @return number of updated rows. */
inline fun <reified T> updateWhere(where: Query, con: Connection?, vararg propsToSet: Pair<KProperty1<T, *>, Any?>) =
    // This method must be inline to obtain generic type, but public inline function can't access private members.
    // So implementation is moved to the separate internal method, that receives type just as a parameter.
    updateWithoutObject(T::class, where, propsToSet, con)

@PublishedApi
internal fun updateWithoutObject(classType: KClass<*>, where: Query, propsToSet: Array<out Pair<KProperty1<*, *>, Any?>>, con: Connection?): Int
{
    val sb = StringBuilder("UPDATE ${entityName(classType)} SET ")
    val bindParams = ArrayList<Any?>(propsToSet.size)

    for ((prop, value) in propsToSet) {
        appendCol(sb, colName(prop), " = ?")
        addValueToBindParams(value, classType, prop, bindParams)
    }
    sb.deleteCharAt(sb.length - 1) // Remove trailing comma

    sb.append(" WHERE ")
    sb.append(where.sql)
    bindParams.addAll(where.bindParams)

    return exec(Query(sb.toString(), bindParams), con)
}