package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlIgnore
import org.sqlpal.unaryMinus
import org.sqlpal.query.exec
import org.sqlpal.query.execWithResult
import org.sqlpal.query.execWithResults
import org.sqlpal.query.insert
import org.sqlpal.query.insertMany
import org.sqlpal.query.readValue
import org.sqlpal.query.select
import kotlin.test.assertEquals
import kotlin.test.assertNotNull
import kotlin.test.assertNull
import kotlin.test.assertTrue

class BatchAndExecTest : H2TestBase() {

    data class Item(
        @Id @AutoGen var id: Long? = null,
        var name: String = "",
        var amount: Int = 0,
        @SqlIgnore var ignored: String = "",
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE item (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255),
                amount INT
            )
        """.trimIndent())
    }

    @AfterEach
    fun clear() {
        exec("DELETE FROM item")
    }

    // ---------- insertMany ----------

    @Test fun `insertMany writes every item`() {
        val items = (1..50).map { Item(name = "n$it", amount = it) }
        val total = insertMany(items)
        assertEquals(50, total)
        assertEquals(50, readValue<Long>(-"SELECT COUNT(*) FROM item"))
    }

    @Test fun `insertMany with empty iterable returns zero`() {
        val total = insertMany<Item>(emptyList())
        assertEquals(0, total)
    }

    @Test fun `insertMany respects SqlIgnore`() {
        val items = listOf(Item(name = "a", amount = 1, ignored = "skip"))
        // If SqlIgnore weren't honored, the INSERT would reference a missing column.
        assertEquals(1, insertMany(items))
    }

    @Test fun `insertMany preserves insertion order semantics`() {
        val list = listOf(Item(name = "x", amount = 7), Item(name = "y", amount = 8))
        insertMany(list)
        val rows = select<Item>(-"1=1 ORDER BY id")
        assertEquals(listOf("x", "y"), rows.map { it.name })
        assertEquals(listOf(7, 8), rows.map { it.amount })
    }

    // ---------- exec ----------

    @Test fun `exec runs a DML query and returns affected count`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 2))
        val n = exec(-"DELETE FROM item WHERE amount = ${1}")
        assertEquals(1, n)
        assertEquals(1, readValue<Long>(-"SELECT COUNT(*) FROM item"))
    }

    @Test fun `exec returns 0 when nothing matched`() {
        val n = exec(-"DELETE FROM item WHERE amount = ${9999}")
        assertEquals(0, n)
    }

    // ---------- execWithResult ----------

    /**
     * `execWithResult` requests generated keys (via `requestGeneratedColumns = true` →
     * `Statement.RETURN_GENERATED_KEYS`), so a successful INSERT returns the generated id.
     *
     * NB: a variable is used instead of a string literal — Terpal folds `${"literal"}`
     * into the SQL text at compile time, so a literal wouldn't become a bind parameter.
     */
    @Test fun `execWithResult returns the generated key`() {
        val name = "first"
        val v = execWithResult(-"INSERT INTO item (name, amount) VALUES (${name}, ${10})")
        assertNotNull(v)
        assertTrue(v is Number, "expected a generated numeric id, got $v")
    }

    @Test fun `execWithResult returns null when no rows affected`() {
        val v = execWithResult(-"DELETE FROM item WHERE amount = ${9999}")
        assertNull(v)
    }

    // ---------- execWithResults ----------

    @Test fun `execWithResults returns the generated-keys map`() {
        val name = "a"
        val result = execWithResults(
            -"INSERT INTO item (name, amount) VALUES (${name}, ${1})",
            autoGenColumns = arrayOf("id")
        )
        assertNotNull(result)
        assertTrue(result!!.containsKey("id"), "expected an 'id' key, got ${result.keys}")
        // H2 returns the generated identity as a Number.
        assertTrue(result["id"] is Number, "expected a numeric id, got ${result["id"]}")
    }

    @Test fun `execWithResults returns null when no rows affected`() {
        val result = execWithResults(
            -"UPDATE item SET amount = ${1} WHERE id = ${-1}",
            autoGenColumns = arrayOf("id")
        )
        assertNull(result)
    }
}
