package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.ArrayStorageType
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlName
import org.sqlpal.SqlPal
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.selectById
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNull

/**
 * Coverage for List / Set / Array mapping, in both storage modes:
 *  - JSON (`SqlPal.storeArraysAs = Json`) — collections serialized to a JSON string,
 *  - native DB arrays (`storeArraysAs = Array`, the default) — backed by H2 `… ARRAY`.
 *
 * Includes nullable collection round-trips and empty collections.
 */
class CollectionTypeTest : H2TestBase() {

    enum class Tag { A, B, C }

    @SqlName("coll_json")
    data class CollJson(
        @Id @AutoGen var id: Long? = null,
        var ints: List<Int> = emptyList(),
        var strs: Set<String> = emptySet(),
        var arr: Array<Int> = emptyArray(),
        var tags: List<Tag> = emptyList(),
        var nints: List<Int>? = null,
    )

    @SqlName("coll_arr")
    data class CollArr(
        @Id @AutoGen var id: Long? = null,
        var ints: List<Int> = emptyList(),
        var strs: Set<String> = emptySet(),
        var nints: List<Int>? = null,
    )

    /** Array-typed properties: boxed `Array<Int>` (→ Integer[]) and unboxed `IntArray` (→ int[], boxed on write). */
    @SqlName("arr_holder")
    data class ArrHolder(
        @Id @AutoGen var id: Long? = null,
        var boxed: Array<Int> = emptyArray(),
        var unboxed: IntArray = IntArray(0),
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE coll_json (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ints VARCHAR(512),
                strs VARCHAR(512),
                arr VARCHAR(512),
                tags VARCHAR(512),
                nints VARCHAR(512)
            )
        """.trimIndent())
        exec("""
            CREATE TABLE coll_arr (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                ints INTEGER ARRAY,
                strs VARCHAR ARRAY,
                nints INTEGER ARRAY
            )
        """.trimIndent())
        exec("""
            CREATE TABLE arr_holder (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                boxed INTEGER ARRAY,
                unboxed INTEGER ARRAY
            )
        """.trimIndent())
    }

    @AfterEach fun clear() {
        exec("DELETE FROM coll_json")
        exec("DELETE FROM coll_arr")
        exec("DELETE FROM arr_holder")
        SqlPal.storeArraysAs = ArrayStorageType.Array
    }

    // ---------- JSON storage ----------

    @Test fun `List Set Array and enum-list round-trip as JSON`() {
        SqlPal.storeArraysAs = ArrayStorageType.Json
        val c = CollJson(
            ints = listOf(1, 2, 3),
            strs = setOf("a", "b"),
            arr = arrayOf(7, 8),
            tags = listOf(Tag.A, Tag.C),
            nints = listOf(9, 10),
        )
        insert(c)
        val r = selectById<CollJson>(c.id!!)
        assertEquals(listOf(1, 2, 3), r.ints)
        assertEquals(setOf("a", "b"), r.strs)
        assertContentEquals(arrayOf(7, 8), r.arr)
        assertEquals(listOf(Tag.A, Tag.C), r.tags)
        assertEquals(listOf(9, 10), r.nints)
    }

    @Test fun `empty collections round-trip as JSON`() {
        SqlPal.storeArraysAs = ArrayStorageType.Json
        val c = CollJson(ints = emptyList(), strs = emptySet(), arr = emptyArray(), tags = emptyList(), nints = emptyList())
        insert(c)
        val r = selectById<CollJson>(c.id!!)
        assertEquals(emptyList(), r.ints)
        assertEquals(emptySet(), r.strs)
        assertEquals(0, r.arr.size)
        assertEquals(emptyList(), r.tags)
        assertEquals(emptyList(), r.nints)
    }

    @Test fun `nullable collection round-trips null as JSON`() {
        SqlPal.storeArraysAs = ArrayStorageType.Json
        val c = CollJson(nints = null)
        insert(c)
        assertNull(selectById<CollJson>(c.id!!).nints)
    }

    // ---------- native DB arrays (default storeArraysAs = Array) ----------
    // Since the B14 fix, native array writes work on H2 too: for non-Postgres drivers
    // SqlPal boxes primitive arrays to Object[] before setObject, and reads convert
    // H2's untyped Array<Any> back to the property's element type. (PostgreSQL keeps
    // its existing path and returns typed arrays directly.)

    @Test fun `List, Set and nullable collection round-trip as native arrays`() {
        val c = CollArr(ints = listOf(1, 2, 3), strs = setOf("a", "b"), nints = listOf(9))
        insert(c)
        val r = selectById<CollArr>(c.id!!)
        assertEquals(listOf(1, 2, 3), r.ints)
        assertEquals(setOf("a", "b"), r.strs)
        assertEquals(listOf(9), r.nints)
    }

    @Test fun `nullable native array round-trips null`() {
        val c = CollArr(ints = listOf(1), strs = setOf("x"), nints = null)
        insert(c)
        assertNull(selectById<CollArr>(c.id!!).nints)
    }

    @Test fun `boxed and unboxed arrays round-trip as native arrays`() {
        // Array<Int> → Integer[]; IntArray → int[] (boxed to Integer[] on write).
        val c = ArrHolder(boxed = arrayOf(7, 8), unboxed = intArrayOf(10, 20))
        insert(c)
        val r = selectById<ArrHolder>(c.id!!)
        assertContentEquals(arrayOf(7, 8), r.boxed)
        assertContentEquals(intArrayOf(10, 20), r.unboxed)
    }

    @Test fun `reads native arrays seeded by raw SQL`() {
        exec("INSERT INTO coll_arr (id, ints, strs, nints) VALUES (100, ARRAY[1,2,3], ARRAY['a','b'], NULL)")
        val r = selectById<CollArr>(100)
        assertEquals(listOf(1, 2, 3), r.ints)
        assertEquals(setOf("a", "b"), r.strs)
        assertNull(r.nints)
    }
}
