package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlIgnore
import org.sqlpal.SqlName
import org.sqlpal.query.*
import org.sqlpal.unaryMinus
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNotNull
import kotlin.test.assertNull

class CrudTest : H2TestBase() {

    data class Item(
        @Id @AutoGen var id: Long? = null,
        var name: String = "",
        var amount: Int = 0,
        @SqlIgnore var transient: String = "ignored",
    )

    @SqlName("renamed_item")
    data class Renamed(
        @Id @AutoGen var id: Long? = null,
        @SqlName("custom_col") var label: String = "",
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE item (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255),
                amount INT
            )
        """.trimIndent())
        exec("""
            CREATE TABLE renamed_item (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                custom_col VARCHAR(255)
            )
        """.trimIndent())
    }

    @AfterEach
    fun clearTables() {
        exec("DELETE FROM item")
        exec("DELETE FROM renamed_item")
    }

    // ---------- insert ----------

    @Test fun `insert returns affected rows and assigns auto-gen id`() {
        val item = Item(name = "foo", amount = 10)
        val n = insert(item)
        assertEquals(1, n)
        assertNotNull(item.id)
        assert(item.id!! > 0) { "expected positive id, got ${item.id}" }
    }

    @Test fun `insert ignores SqlIgnore properties`() {
        val item = Item(name = "x", amount = 1, transient = "should not be persisted")
        insert(item)
        // No 'transient' column exists; the INSERT would have failed if SqlIgnore weren't honored.
        val read = selectById<Item>(item.id!!)
        assertEquals("ignored", read.transient) // unchanged default
    }

    @Test fun `insert with updateAutoGenValues=false leaves id null`() {
        val item = Item(name = "x", amount = 0)
        insert(item, updateAutoGenValues = false)
        assertNull(item.id)
        // The row is there though
        assertEquals(1, select<Item>(-"1=1").size)
    }

    @Test fun `insert honors SqlName on class and property`() {
        val r = Renamed(label = "hello")
        insert(r)
        assertNotNull(r.id)
        val rows = select<Renamed>(-"1=1")
        assertEquals(1, rows.size)
        assertEquals("hello", rows[0].label)
    }

    // ---------- selectById / selectByIdOrNull ----------

    @Test fun `selectById round-trips entity`() {
        val item = Item(name = "round", amount = 7)
        insert(item)
        val found = selectById<Item>(item.id!!)
        assertEquals(item.id, found.id)
        assertEquals("round", found.name)
        assertEquals(7, found.amount)
    }

    @Test fun `selectByIdOrNull returns null when row does not exist`() {
        assertNull(selectByIdOrNull<Item>(999_999))
    }

    @Test fun `selectById throws IllegalArgumentException when not found`() {
        assertFailsWith<IllegalArgumentException> { selectById<Item>(999_999) }
    }

    // ---------- update ----------

    @Test fun `update by id writes all non-ignored properties`() {
        val item = Item(name = "old", amount = 1)
        insert(item)
        item.name = "new"
        item.amount = 99
        val n = update(item)
        assertEquals(1, n)
        val reloaded = selectById<Item>(item.id!!)
        assertEquals("new", reloaded.name)
        assertEquals(99, reloaded.amount)
    }

    @Test fun `update only writes specified properties`() {
        val item = Item(name = "keep", amount = 50)
        insert(item)
        item.name = "changed"
        item.amount = 999
        update(item) { only(::name) }
        val reloaded = selectById<Item>(item.id!!)
        assertEquals("changed", reloaded.name)
        assertEquals(50, reloaded.amount) // unchanged
    }

    @Test fun `update except writes everything but the listed properties`() {
        val item = Item(name = "untouched", amount = 1)
        insert(item)
        item.name = "should-not-change"
        item.amount = 42
        update(item) { except(::name) }
        val reloaded = selectById<Item>(item.id!!)
        assertEquals("untouched", reloaded.name)
        assertEquals(42, reloaded.amount)
    }

    @Test fun `update set updates property and column`() {
        val item = Item(name = "before", amount = 1)
        insert(item)
        update(item) { set(::name to "after") }
        assertEquals("after", item.name) // entity mutated
        val reloaded = selectById<Item>(item.id!!)
        assertEquals("after", reloaded.name)
    }

    @Test fun `update with where clause overrides id-based predicate`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 1))
        val target = Item(name = "filler", amount = 99) // id is null - shouldn't matter
        val n = update(target, where = -"amount = ${1}")
        assertEquals(2, n)
        val all = select<Item>(-"1=1").sortedBy { it.id }
        all.forEach { assertEquals("filler", it.name) }
    }

    @Test fun `update by raw column-name list updates only those`() {
        val item = Item(name = "name1", amount = 1)
        insert(item)
        update(item, listOf("name" to "renamed", "amount" to 100))
        val reloaded = selectById<Item>(item.id!!)
        assertEquals("renamed", reloaded.name)
        assertEquals(100, reloaded.amount)
    }

    @Test fun `static update by where with prop pairs`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 2))
        val n = updateWhere(-"amount >= ${2}", Item::name to "bumped")
        assertEquals(1, n)
        val bumped = "bumped"
        assertEquals(1, select<Item>(-"name = $bumped").size)
    }

    // ---------- delete ----------

    @Test fun `delete by entity removes the row`() {
        val item = Item(name = "x", amount = 1)
        insert(item)
        val n = delete(item)
        assertEquals(1, n)
        assertNull(selectByIdOrNull<Item>(item.id!!))
    }

    @Test fun `delete with where removes matching rows`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 5))
        insert(Item(name = "c", amount = 9))
        val n = delete<Item>(-"amount > ${3}")
        assertEquals(2, n)
        val remaining = select<Item>(-"1=1")
        assertEquals(1, remaining.size)
        assertEquals("a", remaining[0].name)
    }
}
