package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlName
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.selectById
import java.sql.Blob
import java.sql.Clob
import java.util.UUID
import kotlin.test.assertContentEquals
import kotlin.test.assertEquals
import kotlin.test.assertNull

/**
 * Coverage for UUID and the JDBC LOB types (Blob, Clob) handled by
 * `Query.createReader` (`getBlob`/`getClob`/`getObject`) and `setBindParams`.
 *
 * SQLXML is intentionally not exercised here: H2 has no XML type and does not
 * implement `Connection.createSQLXML()`, so SqlPal's SQLXML path (`getSQLXML`)
 * can't be driven on H2. It is covered by code review only (see audit).
 */
class LobUuidTest : H2TestBase() {

    @SqlName("uuid_holder")
    data class UuidHolder(
        @Id @AutoGen var id: Long? = null,
        var u: UUID = UUID(0, 0),
        var nu: UUID? = null,
    )

    @SqlName("lob_holder")
    data class LobHolder(
        @Id @AutoGen var id: Long? = null,
        var blob: Blob? = null,
        var clob: Clob? = null,
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE uuid_holder (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                u UUID,
                nu UUID
            )
        """.trimIndent())
        // H2 PostgreSQL mode rejects the `BLOB`/`CLOB` keywords; use the SQL-standard names.
        exec("""
            CREATE TABLE lob_holder (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                blob BINARY LARGE OBJECT,
                clob CHARACTER LARGE OBJECT
            )
        """.trimIndent())
    }

    @AfterEach fun clear() {
        exec("DELETE FROM uuid_holder")
        exec("DELETE FROM lob_holder")
    }

    // ---------- UUID ----------

    @Test fun `UUID round-trips and nullable UUID round-trips null`() {
        val id = UUID.randomUUID()
        val h = UuidHolder(u = id, nu = null)
        insert(h)
        val r = selectById<UuidHolder>(h.id!!)
        assertEquals(id, r.u)
        assertNull(r.nu)
    }

    @Test fun `nullable UUID round-trips non-null`() {
        val a = UUID.randomUUID()
        val b = UUID.randomUUID()
        val h = UuidHolder(u = a, nu = b)
        insert(h)
        val r = selectById<UuidHolder>(h.id!!)
        assertEquals(a, r.u)
        assertEquals(b, r.nu)
    }

    @Test fun `UUID is usable as a bind parameter in WHERE`() {
        val a = UUID.randomUUID()
        insert(UuidHolder(u = a))
        insert(UuidHolder(u = UUID.randomUUID()))
        val matched = org.sqlpal.query.select<UuidHolder>(-"u = $a")
        assertEquals(1, matched.size)
        assertEquals(a, matched[0].u)
    }

    // ---------- Blob / Clob ----------
    // LOBs created via the JDBC connection are valid for that connection, so the
    // whole round-trip runs inside a single SqlPal.withConnection block.

    @Test fun `Blob round-trips its bytes`() {
        val bytes = byteArrayOf(1, 2, 3, 4, 5, 127, -1, -128)
        SqlPal.withConnection { con ->
            val blob = con.createBlob().apply { setBytes(1, bytes) }
            val h = LobHolder(blob = blob)
            insert(h, con)
            val r = selectById<LobHolder>(h.id!!, con)
            val out = r.blob!!.let { it.getBytes(1, it.length().toInt()) }
            assertContentEquals(bytes, out)
            assertNull(r.clob)
        }
    }

    @Test fun `Clob round-trips its text`() {
        val text = "the quick brown fox — ünïcödé"
        SqlPal.withConnection { con ->
            val clob = con.createClob().apply { setString(1, text) }
            val h = LobHolder(clob = clob)
            insert(h, con)
            val r = selectById<LobHolder>(h.id!!, con)
            val out = r.clob!!.let { it.getSubString(1, it.length().toInt()) }
            assertEquals(text, out)
            assertNull(r.blob)
        }
    }
}
