package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlName
import org.sqlpal.SqlPal
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.selectById
import kotlin.test.assertEquals

/**
 * Verifies class/property → table/column name mapping through the PUBLIC API only:
 * a successful insert + select round-trip against a table whose names match what
 * SqlPal is expected to generate proves the names were produced correctly (a wrong
 * name would reference a non-existent table/column and fail). Replaces the former
 * unit tests that called the internal `entityName` / `colName` helpers.
 *
 * The H2 datasource uses `DATABASE_TO_LOWER=TRUE`, so unquoted identifiers are
 * stored lower-cased — matching SqlPal's lower-cased output.
 */
class NameMappingTest : H2TestBase() {

    // camelCase → snake_case (default). `SomeUPPERThing` → `some_u_p_p_e_r_thing`.
    data class CamelThing(
        @Id @AutoGen var id: Long? = null,
        var firstName: String = "",
        var SomeUPPERThing: Int = 0,
    )

    // @SqlName overrides on both the class and a property.
    @SqlName("custom_tbl")
    data class Renamed(
        @Id @AutoGen var id: Long? = null,
        @SqlName("custom_col") var label: String = "",
    )

    // Used with convertNamesToSnakeCase = false: name kept as-is (`firstName`).
    data class NoConv(
        @Id @AutoGen var id: Long? = null,
        var firstName: String = "",
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE camel_thing (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                first_name VARCHAR(255),
                some_u_p_p_e_r_thing INT
            )
        """.trimIndent())
        exec("""
            CREATE TABLE custom_tbl (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                custom_col VARCHAR(255)
            )
        """.trimIndent())
        // No snake_case conversion: identifiers kept as written (H2 lower-cases them).
        exec("""
            CREATE TABLE NoConv (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                firstName VARCHAR(255)
            )
        """.trimIndent())
    }

    @AfterEach fun clear() {
        exec("DELETE FROM camel_thing")
        exec("DELETE FROM custom_tbl")
        exec("DELETE FROM NoConv")
        // Restore the library default for the other test classes.
        SqlPal.convertNamesToSnakeCase = true
    }

    @Test fun `camelCase class and property names map to snake_case`() {
        SqlPal.convertNamesToSnakeCase = true
        val t = CamelThing(firstName = "Kate", SomeUPPERThing = 7)
        insert(t) // would fail unless table=camel_thing, cols=first_name, some_u_p_p_e_r_thing
        val r = selectById<CamelThing>(t.id!!)
        assertEquals("Kate", r.firstName)
        assertEquals(7, r.SomeUPPERThing)
    }

    @Test fun `SqlName overrides table and column names`() {
        val r = Renamed(label = "hello")
        insert(r) // would fail unless table=custom_tbl, col=custom_col
        // The select path also resolves the @SqlName for the constructor parameter.
        assertEquals("hello", selectById<Renamed>(r.id!!).label)
    }

    @Test fun `disabling snake_case keeps original property names`() {
        SqlPal.convertNamesToSnakeCase = false
        val n = NoConv(firstName = "Bob")
        // With conversion ON this would look for column `first_name` (absent) and fail.
        insert(n)
        assertEquals("Bob", selectById<NoConv>(n.id!!).firstName)
    }
}
