package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlName
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.select
import org.sqlpal.query.selectById
import java.sql.SQLException
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Coverage for the scalar value types handled by `Query.createReader` /
 * `setBindParams`: Long, Byte, Short, Float, Double, Boolean, String, Int.
 *
 * For each: non-null round-trip (with boundary values), nullable round-trip
 * (null and non-null), and — for value types — the documented behavior that a
 * NULL read into a non-nullable property throws (audit-confirmed by the
 * `valueTypeReader` non-null branch).
 */
class ScalarTypeTest : H2TestBase() {

    @SqlName("scalars")
    data class Scalars(
        @Id @AutoGen var id: Long? = null,
        var aLong: Long = 0,
        var aByte: Byte = 0,
        var aShort: Short = 0,
        var aFloat: Float = 0f,
        var aDouble: Double = 0.0,
        var aBoolean: Boolean = false,
        var aString: String = "",
        var anInt: Int = 0,
    )

    @SqlName("nullable_scalars")
    data class NullableScalars(
        @Id @AutoGen var id: Long? = null,
        var aLong: Long? = null,
        var aByte: Byte? = null,
        var aShort: Short? = null,
        var aFloat: Float? = null,
        var aDouble: Double? = null,
        var aBoolean: Boolean? = null,
        var aString: String? = null,
        var anInt: Int? = null,
    )

    private val scalarColumns = """
        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        a_long BIGINT,
        a_byte SMALLINT,
        a_short SMALLINT,
        a_float REAL,
        a_double DOUBLE PRECISION,
        a_boolean BOOLEAN,
        a_string VARCHAR(255),
        an_int INT
    """.trimIndent()

    override fun createSchema() {
        exec("CREATE TABLE scalars ($scalarColumns)")
        exec("CREATE TABLE nullable_scalars ($scalarColumns)")
    }

    @AfterEach fun clear() {
        exec("DELETE FROM scalars")
        exec("DELETE FROM nullable_scalars")
    }

    // ---------- non-null round trips ----------

    @Test fun `non-null scalar types round-trip at boundary values`() {
        val s = Scalars(
            aLong = Long.MAX_VALUE,
            aByte = Byte.MIN_VALUE,
            aShort = Short.MAX_VALUE,
            aFloat = 3.5f,
            aDouble = 2.718281828459045,
            aBoolean = true,
            aString = "héllo",
            anInt = Int.MIN_VALUE,
        )
        insert(s)
        val r = selectById<Scalars>(s.id!!)
        assertEquals(Long.MAX_VALUE, r.aLong)
        assertEquals(Byte.MIN_VALUE, r.aByte)
        assertEquals(Short.MAX_VALUE, r.aShort)
        assertEquals(3.5f, r.aFloat)
        assertEquals(2.718281828459045, r.aDouble)
        assertEquals(true, r.aBoolean)
        assertEquals("héllo", r.aString)
        assertEquals(Int.MIN_VALUE, r.anInt)
    }

    @Test fun `boolean false round-trips`() {
        val s = Scalars(aBoolean = false)
        insert(s)
        assertEquals(false, selectById<Scalars>(s.id!!).aBoolean)
    }

    // ---------- nullable round trips ----------

    @Test fun `nullable scalar types round-trip null`() {
        val s = NullableScalars() // everything null
        insert(s)
        val r = selectById<NullableScalars>(s.id!!)
        assertNull(r.aLong)
        assertNull(r.aByte)
        assertNull(r.aShort)
        assertNull(r.aFloat)
        assertNull(r.aDouble)
        assertNull(r.aBoolean)
        assertNull(r.aString)
        assertNull(r.anInt)
    }

    @Test fun `nullable scalar types round-trip non-null`() {
        val s = NullableScalars(
            aLong = 10L,
            aByte = 1,
            aShort = 2,
            aFloat = 1.5f,
            aDouble = 2.5,
            aBoolean = false,
            aString = "x",
            anInt = 7,
        )
        insert(s)
        val r = selectById<NullableScalars>(s.id!!)
        assertEquals(10L, r.aLong)
        assertEquals(1.toByte(), r.aByte)
        assertEquals(2.toShort(), r.aShort)
        assertEquals(1.5f, r.aFloat)
        assertEquals(2.5, r.aDouble)
        assertEquals(false, r.aBoolean)
        assertEquals("x", r.aString)
        assertEquals(7, r.anInt)
    }

    // ---------- NULL into a non-nullable value-type property throws ----------

    /** Seeds one fully-populated row, NULLs a single column, then reads it back.
     *  The reader walks constructor params in order and throws on the first NULL
     *  found in a non-nullable value type. */
    private fun assertNullColumnThrows(nullColumn: String, propName: String) {
        exec(
            "INSERT INTO scalars (a_long, a_byte, a_short, a_float, a_double, a_boolean, a_string, an_int) " +
                "VALUES (1, 1, 1, 1, 1, TRUE, 'x', 1)"
        )
        exec("UPDATE scalars SET $nullColumn = NULL")
        val ex = assertFailsWith<SQLException> { select<Scalars>(-"1=1") }
        assertTrue(
            ex.message!!.contains(propName),
            "expected error to mention property '$propName', got: ${ex.message}"
        )
    }

    @Test fun `NULL in non-null Long throws`() = assertNullColumnThrows("a_long", "aLong")
    @Test fun `NULL in non-null Byte throws`() = assertNullColumnThrows("a_byte", "aByte")
    @Test fun `NULL in non-null Short throws`() = assertNullColumnThrows("a_short", "aShort")
    @Test fun `NULL in non-null Float throws`() = assertNullColumnThrows("a_float", "aFloat")
    @Test fun `NULL in non-null Double throws`() = assertNullColumnThrows("a_double", "aDouble")
    @Test fun `NULL in non-null Boolean throws`() = assertNullColumnThrows("a_boolean", "aBoolean")
    @Test fun `NULL in non-null Int throws`() = assertNullColumnThrows("an_int", "anInt")

    /**
     * Documents a sharp edge in NULL handling by type category:
     *  - value types (Int/Long/…) → SqlPal's `valueTypeReader` raises a friendly
     *    SQLException naming the property (tested above);
     *  - reference types like String → read with `getString` (returns null), so the
     *    null is only caught later by the Kotlin constructor's non-null check, which
     *    throws a bare NullPointerException with a far less helpful message.
     * (Worth an audit note: the error quality is inconsistent across types.)
     */
    @Test fun `NULL in non-null String fails at the constructor null-check`() {
        exec(
            "INSERT INTO scalars (a_long, a_byte, a_short, a_float, a_double, a_boolean, a_string, an_int) " +
                "VALUES (1, 1, 1, 1, 1, TRUE, NULL, 1)"
        )
        // The reflective constructor call wraps the failure; the root cause is the
        // Kotlin non-null parameter check (a bare NPE), not SqlPal's friendly SQLException.
        val ex = assertFailsWith<Exception> { select<Scalars>(-"1=1") }
        val root = generateSequence(ex as Throwable) { it.cause }.last()
        assertTrue(root is NullPointerException, "expected root cause NPE, got $root")
        assertTrue(
            root.message?.contains("aString") == true,
            "expected NPE to mention the non-null parameter, got: ${root.message}"
        )
    }
}
