package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlIgnore
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.read
import org.sqlpal.query.readOne
import org.sqlpal.query.readOneOrNull
import org.sqlpal.query.readValue
import org.sqlpal.query.readValueOrNull
import org.sqlpal.query.readValues
import org.sqlpal.query.select
import org.sqlpal.query.selectOne
import org.sqlpal.query.selectOneOrNull
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertNull
import kotlin.test.assertTrue

class SelectReadTest : H2TestBase() {

    data class Item(
        @Id @AutoGen var id: Long? = null,
        var name: String = "",
        var amount: Int = 0,
    )

    /** Demonstrates optional ctor params (excluded when includeOptional=false). */
    data class WithOptional(
        @Id @AutoGen var id: Long? = null,
        val required: String,
        val optional: String = "default",
        @SqlIgnore var ignored: String = "ignored",
    ) {
        var afterCtor: String = ""
    }

    override fun createSchema() {
        exec("""
            CREATE TABLE item (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name VARCHAR(255),
                amount INT
            )
        """.trimIndent())
        exec("""
            CREATE TABLE with_optional (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                required VARCHAR(255),
                optional VARCHAR(255),
                after_ctor VARCHAR(255)
            )
        """.trimIndent())
    }

    @AfterEach
    fun clearTables() {
        exec("DELETE FROM item")
        exec("DELETE FROM with_optional")
    }

    // ---------- select with where ----------

    @Test fun `select returns matching rows`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 5))
        insert(Item(name = "c", amount = 9))
        val rows = select<Item>(-"amount >= ${5} ORDER BY amount")
        assertEquals(2, rows.size)
        assertEquals("b", rows[0].name)
        assertEquals("c", rows[1].name)
    }

    @Test fun `select with no rows returns empty list`() {
        val rows = select<Item>(-"1=0")
        assertEquals(0, rows.size)
    }

    @Test fun `IN with a collection filters by membership`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 2))
        insert(Item(name = "c", amount = 3))
        val wanted = listOf(1, 3)
        val rows = select<Item>(-"amount IN $wanted ORDER BY amount")
        assertEquals(listOf(1, 3), rows.map { it.amount })
    }

    @Test fun `IN with an empty collection matches nothing (B1)`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 2))
        // Empty IN renders as `amount IN (NULL)` → valid SQL that matches no rows.
        val empty = emptyList<Int>()
        val rows = select<Item>(-"amount IN $empty")
        assertEquals(0, rows.size)
    }

    @Test fun `select with capacity hint still loads all rows`() {
        repeat(5) { insert(Item(name = "n$it", amount = it)) }
        val rows = select<Item>(-"1=1 ORDER BY amount", capacity = 2)
        assertEquals(5, rows.size)
    }

    @Test fun `selectOne returns the first row`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 5))
        val row = selectOne<Item>(-"1=1 ORDER BY amount")
        assertEquals("a", row.name)
    }

    @Test fun `selectOneOrNull returns null on empty result`() {
        assertNull(selectOneOrNull<Item>(-"1=0"))
    }

    @Test fun `selectOne throws on empty result`() {
        assertFailsWith<IllegalArgumentException> { selectOne<Item>(-"1=0") }
    }

    @Test fun `includeOptional true loads optional ctor params and mutable props`() {
        ds.connection.use { c ->
            c.prepareStatement(
                "INSERT INTO with_optional (required, optional, after_ctor) VALUES (?, ?, ?)"
            ).use {
                it.setString(1, "req")
                it.setString(2, "opt-val")
                it.setString(3, "after-val")
                it.executeUpdate()
            }
        }
        val row = selectOne<WithOptional>(-"1=1", includeOptional = true)
        assertEquals("req", row.required)
        assertEquals("opt-val", row.optional)
        assertEquals("after-val", row.afterCtor)
    }

    @Test fun `includeOptional false skips optional ctor params and mutable props`() {
        ds.connection.use { c ->
            c.prepareStatement(
                "INSERT INTO with_optional (required, optional, after_ctor) VALUES (?, ?, ?)"
            ).use {
                it.setString(1, "req2")
                it.setString(2, "should-be-ignored")
                it.setString(3, "should-also-be-ignored")
                it.executeUpdate()
            }
        }
        val row = selectOne<WithOptional>(-"1=1", includeOptional = false)
        assertEquals("req2", row.required)
        assertEquals("default", row.optional) // ctor default
        assertEquals("", row.afterCtor)       // class-body default
    }

    // ---------- readValue / readValues ----------

    @Test fun `readValue returns first column of first row`() {
        insert(Item(name = "x", amount = 42))
        val n = readValue<Int>(-"SELECT amount FROM item")
        assertEquals(42, n)
    }

    @Test fun `readValueOrNull returns null when no rows`() {
        assertNull(readValueOrNull<Int>(-"SELECT amount FROM item WHERE 1=0"))
    }

    @Test fun `readValue throws when no rows`() {
        assertFailsWith<IllegalArgumentException> { readValue<Int>(-"SELECT amount FROM item WHERE 1=0") }
    }

    @Test fun `readValues returns first column of every row`() {
        listOf(1, 2, 3).forEach { insert(Item(name = "n", amount = it)) }
        val amounts = readValues<Int>(-"SELECT amount FROM item ORDER BY amount")
        assertEquals(listOf(1, 2, 3), amounts)
    }

    @Test fun `readValue returns string column`() {
        insert(Item(name = "hello", amount = 0))
        val s = readValue<String>(-"SELECT name FROM item")
        assertEquals("hello", s)
    }

    // ---------- readOne / readOneOrNull / read ----------

    @Test fun `readOne maps via primary constructor`() {
        insert(Item(name = "ro", amount = 7))
        val row = readOne<Item>(-"SELECT id, name, amount FROM item")
        assertEquals("ro", row.name)
        assertEquals(7, row.amount)
    }

    @Test fun `readOneOrNull returns null for empty result`() {
        assertNull(readOneOrNull<Item>(-"SELECT id, name, amount FROM item WHERE 1=0"))
    }

    @Test fun `read with createItem callback maps each row manually`() {
        insert(Item(name = "a", amount = 1))
        insert(Item(name = "b", amount = 2))
        val pairs = read(-"SELECT name, amount FROM item ORDER BY amount") { rs ->
            rs.getString("name") to rs.getInt("amount")
        }
        assertEquals(listOf("a" to 1, "b" to 2), pairs)
    }

    @Test fun `read with capacity uses ArrayList of that initial capacity`() {
        repeat(3) { insert(Item(name = "n", amount = it)) }
        // Capacity is only a hint; verify behavior still loads all rows.
        val rows = read(-"SELECT name, amount FROM item ORDER BY amount", capacity = 1) { rs ->
            rs.getInt("amount")
        }
        assertEquals(listOf(0, 1, 2), rows)
    }

    @Test fun `read with read-time mapping ignores selected column order`() {
        insert(Item(name = "z", amount = 99))
        // SELECT in reverse order - mapper looks up columns by name so it still works.
        val row = readOne<Item>(-"SELECT amount, name, id FROM item")
        assertEquals("z", row.name)
        assertEquals(99, row.amount)
    }

    // ---------- NULL handling in non-nullable property ----------

    @Test fun `null value in non-nullable column throws on read`() {
        ds.connection.use { c ->
            c.createStatement().use { it.execute("INSERT INTO item (name, amount) VALUES ('n', NULL)") }
        }
        val ex = assertFailsWith<java.sql.SQLException> {
            read<Item>(-"SELECT id, name, amount FROM item")
        }
        assertTrue(ex.message!!.contains("NULL"), "expected SQLException to mention NULL, got: ${ex.message}")
    }
}
