package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.SqlPal
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.select
import org.sqlpal.transaction
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue

class TransactionTest : H2TestBase() {

    data class Account(
        @Id @AutoGen var id: Long? = null,
        var balance: Int = 0,
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE account (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                balance INT
            )
        """.trimIndent())
    }

    @AfterEach
    fun clear() {
        exec("DELETE FROM account")
    }

    @Test fun `commits work on normal block return`() {
        transaction { con ->
            insert(Account(balance = 100), con)
            insert(Account(balance = 200), con)
        }
        val rows = select<Account>(-"1=1")
        assertEquals(2, rows.size)
    }

    @Test fun `rolls back on exception and rethrows`() {
        val ex = assertFailsWith<RuntimeException> {
            transaction { con ->
                insert(Account(balance = 1), con)
                insert(Account(balance = 2), con)
                throw RuntimeException("boom")
            }
        }
        assertEquals("boom", ex.message)
        assertEquals(0, select<Account>(-"1=1").size)
    }

    @Test fun `restores autoCommit on the connection after commit`() {
        SqlPal.withConnection { con ->
            con.autoCommit = true
            transaction(con) { insert(Account(balance = 5), it) }
            assertTrue(con.autoCommit, "autoCommit should be restored to true after transaction")
        }
    }

    @Test fun `restores autoCommit even when block throws`() {
        SqlPal.withConnection { con ->
            con.autoCommit = false
            assertFailsWith<RuntimeException> {
                transaction(con) {
                    insert(Account(balance = 5), it)
                    throw RuntimeException("err")
                }
            }
            // Original autoCommit was false; should still be false.
            assertTrue(!con.autoCommit)
        }
    }

    @Test fun `nested transaction reuses the outer connection`() {
        transaction { outer ->
            insert(Account(balance = 1), outer)
            transaction(outer) { inner ->
                insert(Account(balance = 2), inner)
            }
        }
        assertEquals(2, select<Account>(-"1=1").size)
    }

    @Test fun `transaction returns the block result`() {
        val sum = transaction { con ->
            insert(Account(balance = 10), con)
            insert(Account(balance = 20), con)
            select<Account>(-"1=1", con).sumOf { it.balance }
        }
        assertEquals(30, sum)
    }
}
