package org.sqlpal

import org.junit.jupiter.api.AfterEach
import org.junit.jupiter.api.Test
import org.sqlpal.ArrayStorageType
import org.sqlpal.AutoGen
import org.sqlpal.Id
import org.sqlpal.Mapper
import org.sqlpal.SqlName
import org.sqlpal.SqlPal
import org.sqlpal.ValueMapper
import org.sqlpal.unaryMinus
import org.sqlpal.query.insert
import org.sqlpal.query.readValue
import org.sqlpal.query.select
import org.sqlpal.query.selectById
import java.math.BigDecimal
import java.sql.PreparedStatement
import java.sql.ResultSet
import java.time.Instant
import java.time.LocalDate
import java.time.LocalDateTime
import java.time.LocalTime
import java.time.OffsetDateTime
import java.time.OffsetTime
import java.time.ZoneId
import java.time.ZoneOffset
import java.time.ZonedDateTime
import java.util.Currency
import kotlin.reflect.KClass
import kotlin.test.assertEquals
import kotlin.test.assertNull
import kotlin.test.assertTrue

/**
 * Type-mapping tests against H2.
 *
 * NOTE on enums: since the B13 fix, enum binding is dialect-aware — PostgreSQL uses
 * `setObject(i, value, Types.OTHER)`, every other database (incl. H2) uses
 * `setString(i, value.name)`. So enum *writes* now work on H2 and are tested here
 * alongside the (always portable) `getString` → `toEnum` read path.
 */
class TypeMappingTest : H2TestBase() {

    enum class Color { Red, Green, Blue }

    @SqlName("variety")
    data class Variety(
        @Id @AutoGen var id: Long? = null,
        var birthDate: LocalDate = LocalDate.of(2000, 1, 1),
        var moment: LocalDateTime = LocalDateTime.of(2000, 1, 1, 0, 0),
        var atTime: LocalTime = LocalTime.of(0, 0),
        var price: BigDecimal = BigDecimal.ZERO,
        var currency: Currency = Currency.getInstance("USD"),
        var nullableInt: Int? = null,
        var nullableStr: String? = null,
    )

    @SqlName("enum_holder")
    data class EnumHolder(
        @Id @AutoGen var id: Long? = null,
        var color: Color = Color.Red,
    )

    /** Time-zone-aware JSR-310 types: OffsetTime/OffsetDateTime go through getObject;
     *  ZonedDateTime and Instant are converted via toOffsetDateTime()/atOffset(UTC). */
    @SqlName("temporal_box")
    data class TemporalBox(
        @Id @AutoGen var id: Long? = null,
        var offsetTime: OffsetTime = OffsetTime.of(0, 0, 0, 0, ZoneOffset.UTC),
        var offsetDateTime: OffsetDateTime = OffsetDateTime.of(2000, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC),
        var zoned: ZonedDateTime = ZonedDateTime.of(2000, 1, 1, 0, 0, 0, 0, ZoneOffset.UTC),
        var instant: Instant = Instant.EPOCH,
    )

    @SqlName("unsigned_box")
    data class UnsignedBox(
        @Id @AutoGen var id: Long? = null,
        var u8: UByte = 0u,
        var u16: UShort = 0u,
        var u32: UInt = 0u,
        var u64: ULong = 0u,
    )

    /** Holds a List<Int> serialized as JSON. Column is `vals` (not the reserved `values`). */
    @SqlName("json_list")
    data class JsonList(
        @Id @AutoGen var id: Long? = null,
        var vals: List<Int> = emptyList(),
    )

    /** Demonstrates the @Mapper annotation: an int stored as a 0/1 char. */
    object IntAs01CharMapper : ValueMapper {
        override fun readValue(resultSet: ResultSet, colIndex: Int): Any? {
            val s = resultSet.getString(colIndex) ?: return null
            return if (s == "1") 1 else 0
        }

        override fun writeValue(value: Any?, statement: PreparedStatement, paramIndex: Int, componentType: KClass<*>?): Boolean {
            if (value !is Int) return false
            statement.setString(paramIndex, if (value == 0) "0" else "1")
            return true
        }
    }

    data class WithCustomMapped(
        @Id @AutoGen var id: Long? = null,
        @Mapper(IntAs01CharMapper::class) var flag: Int = 0,
    )

    /** A type used ONLY by the global-mapper test, so registering a process-wide
     *  mapper for it can't leak into any other test (no removal API needed). */
    data class Money(val cents: Long)

    object MoneyMapper : ValueMapper {
        override fun readValue(resultSet: ResultSet, colIndex: Int): Any? {
            val v = resultSet.getLong(colIndex)
            return if (resultSet.wasNull()) null else Money(v)
        }

        override fun writeValue(value: Any?, statement: PreparedStatement, paramIndex: Int, componentType: KClass<*>?): Boolean {
            if (value !is Money) return false
            statement.setLong(paramIndex, value.cents)
            return true
        }
    }

    @SqlName("money_holder")
    data class MoneyHolder(
        @Id @AutoGen var id: Long? = null,
        var price: Money = Money(0),
    )

    override fun createSchema() {
        exec("""
            CREATE TABLE variety (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                birth_date DATE,
                moment TIMESTAMP,
                at_time TIME,
                price DECIMAL(20, 4),
                currency VARCHAR(3),
                nullable_int INT,
                nullable_str VARCHAR(255)
            )
        """.trimIndent())
        exec("""
            CREATE TABLE enum_holder (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                color VARCHAR(16)
            )
        """.trimIndent())
        exec("""
            CREATE TABLE temporal_box (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                offset_time TIME(9) WITH TIME ZONE,
                offset_date_time TIMESTAMP(9) WITH TIME ZONE,
                zoned TIMESTAMP(9) WITH TIME ZONE,
                instant TIMESTAMP(9) WITH TIME ZONE
            )
        """.trimIndent())
        exec("""
            CREATE TABLE unsigned_box (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                u8  SMALLINT,
                u16 INT,
                u32 BIGINT,
                u64 BIGINT
            )
        """.trimIndent())
        exec("""
            CREATE TABLE json_list (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                vals VARCHAR(1024)
            )
        """.trimIndent())
        exec("""
            CREATE TABLE with_custom_mapped (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                flag VARCHAR(2)
            )
        """.trimIndent())
        exec("""
            CREATE TABLE money_holder (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                price BIGINT
            )
        """.trimIndent())
    }

    @AfterEach
    fun clear() {
        exec("DELETE FROM variety")
        exec("DELETE FROM enum_holder")
        exec("DELETE FROM temporal_box")
        exec("DELETE FROM unsigned_box")
        exec("DELETE FROM json_list")
        exec("DELETE FROM with_custom_mapped")
        exec("DELETE FROM money_holder")
        // Restore array-storage default (some tests flip this).
        SqlPal.storeArraysAs = ArrayStorageType.Array
    }

    // ---------- Enum read + write ----------
    // Since the B13 fix, enum binding is portable: on non-PostgreSQL databases
    // (incl. H2) it goes through setString(value.name), so enum WRITES work here too.

    @Test fun `enum is read back from a string column`() {
        exec("INSERT INTO enum_holder (id, color) VALUES (1, 'Green')")
        val r = selectById<EnumHolder>(1)
        assertEquals(Color.Green, r.color)
    }

    @Test fun `enum reading works for every constant`() {
        exec("INSERT INTO enum_holder (id, color) VALUES (1, 'Red'), (2, 'Green'), (3, 'Blue')")
        val all = select<EnumHolder>(-"1=1 ORDER BY id")
        assertEquals(listOf(Color.Red, Color.Green, Color.Blue), all.map { it.color })
    }

    @Test fun `enum is written and round-trips via insert`() {
        val h = EnumHolder(color = Color.Blue)
        insert(h)
        // stored as the constant name…
        assertEquals("Blue", readValue<String>(-"SELECT color FROM enum_holder WHERE id = ${h.id!!}"))
        // …and reads back as the enum.
        assertEquals(Color.Blue, selectById<EnumHolder>(h.id!!).color)
    }

    @Test fun `enum is usable as a bind parameter in WHERE`() {
        insert(EnumHolder(color = Color.Red))
        insert(EnumHolder(color = Color.Blue))
        insert(EnumHolder(color = Color.Blue))
        val blues = select<EnumHolder>(-"color = ${Color.Blue} ORDER BY id")
        assertEquals(2, blues.size)
        blues.forEach { assertEquals(Color.Blue, it.color) }
    }

    // ---------- JSR-310 date types ----------

    @Test fun `LocalDate round-trips`() {
        val d = LocalDate.of(2024, 3, 14)
        val v = Variety(birthDate = d)
        insert(v)
        assertEquals(d, selectById<Variety>(v.id!!).birthDate)
    }

    @Test fun `LocalDateTime round-trips at microsecond precision`() {
        // H2 TIMESTAMP keeps microsecond precision; 123_456_000 ns = 123456 µs exactly.
        val dt = LocalDateTime.of(2024, 3, 14, 12, 30, 45, 123_456_000)
        val v = Variety(moment = dt)
        insert(v)
        assertEquals(dt, selectById<Variety>(v.id!!).moment)
    }

    @Test fun `LocalTime round-trips`() {
        val t = LocalTime.of(13, 0, 5)
        val v = Variety(atTime = t)
        insert(v)
        assertEquals(t, selectById<Variety>(v.id!!).atTime)
    }

    // ---------- Time-zone-aware JSR-310 types ----------

    @Test fun `OffsetDateTime round-trips preserving the offset`() {
        val odt = OffsetDateTime.of(2024, 3, 14, 12, 30, 45, 123_456_000, ZoneOffset.ofHours(3))
        val box = TemporalBox(offsetDateTime = odt)
        insert(box)
        val read = selectById<TemporalBox>(box.id!!).offsetDateTime
        // Compare instants (robust to any offset normalization by the DB)…
        assertTrue(odt.isEqual(read), "expected same instant as $odt, got $read")
        // …and confirm H2 preserves the original offset.
        assertEquals(odt, read)
    }

    @Test fun `OffsetTime round-trips preserving the offset`() {
        val ot = OffsetTime.of(13, 0, 5, 0, ZoneOffset.ofHours(3))
        val box = TemporalBox(offsetTime = ot)
        insert(box)
        assertEquals(ot, selectById<TemporalBox>(box.id!!).offsetTime)
    }

    @Test fun `ZonedDateTime with an offset zone round-trips exactly`() {
        // SqlPal stores a ZonedDateTime as its OffsetDateTime, then rebuilds it via
        // toZonedDateTime() on read. When the original zone IS an offset, the round-trip
        // is exact.
        val zdt = ZonedDateTime.of(2024, 3, 14, 12, 30, 45, 0, ZoneOffset.ofHours(3))
        val box = TemporalBox(zoned = zdt)
        insert(box)
        assertEquals(zdt, selectById<TemporalBox>(box.id!!).zoned)
    }

    @Test fun `ZonedDateTime with a named zone keeps the instant but degrades the zone to an offset`() {
        // Because storage goes through OffsetDateTime, the named region ("Europe/Paris")
        // is lost on read — only the offset survives. The instant is preserved.
        val zdt = ZonedDateTime.of(2024, 3, 14, 12, 30, 45, 0, ZoneId.of("Europe/Paris"))
        val box = TemporalBox(zoned = zdt)
        insert(box)
        val read = selectById<TemporalBox>(box.id!!).zoned
        assertEquals(zdt.toInstant(), read.toInstant())
        assertTrue(read.zone is ZoneOffset, "expected zone to degrade to an offset, got ${read.zone}")
    }

    @Test fun `Instant round-trips`() {
        val instant = Instant.parse("2024-03-14T09:30:45.123456Z")
        val box = TemporalBox(instant = instant)
        insert(box)
        assertEquals(instant, selectById<TemporalBox>(box.id!!).instant)
    }

    // ---------- BigDecimal ----------

    @Test fun `BigDecimal round-trips with scale preserved`() {
        val price = BigDecimal("123.4500")
        val v = Variety(price = price)
        insert(v)
        val read = selectById<Variety>(v.id!!).price
        assertEquals(0, price.compareTo(read), "expected $price, got $read")
    }

    // ---------- Currency (built-in: stored as ISO code string) ----------

    @Test fun `Currency stored as ISO code and read back`() {
        val v = Variety(currency = Currency.getInstance("EUR"))
        insert(v)
        assertEquals("EUR", readValue<String>(-"SELECT currency FROM variety WHERE id = ${v.id!!}"))
        assertEquals(Currency.getInstance("EUR"), selectById<Variety>(v.id!!).currency)
    }

    // ---------- Nullable columns ----------

    @Test fun `nullable columns round-trip null`() {
        val v = Variety(nullableInt = null, nullableStr = null)
        insert(v)
        val r = selectById<Variety>(v.id!!)
        assertNull(r.nullableInt)
        assertNull(r.nullableStr)
    }

    @Test fun `nullable columns round-trip non-null`() {
        val v = Variety(nullableInt = 42, nullableStr = "yes")
        insert(v)
        val r = selectById<Variety>(v.id!!)
        assertEquals(42, r.nullableInt)
        assertEquals("yes", r.nullableStr)
    }

    // ---------- Unsigned types ----------

    @Test fun `unsigned types round-trip through signed storage`() {
        val box = UnsignedBox(u8 = 200u, u16 = 60_000u, u32 = 3_000_000_000u, u64 = 12345uL)
        insert(box)
        val r = selectById<UnsignedBox>(box.id!!)
        assertEquals(200u, r.u8)
        assertEquals(60_000u, r.u16)
        assertEquals(3_000_000_000u, r.u32)
        assertEquals(12345uL, r.u64)
    }

    // ---------- Custom mapper via @Mapper annotation ----------

    @Test fun `custom Mapper translates int to 0 or 1 char`() {
        val a = WithCustomMapped(flag = 1)
        insert(a)
        assertEquals("1", readValue<String>(-"SELECT flag FROM with_custom_mapped WHERE id = ${a.id!!}"))

        val b = WithCustomMapped(flag = 0)
        insert(b)
        assertEquals("0", readValue<String>(-"SELECT flag FROM with_custom_mapped WHERE id = ${b.id!!}"))
    }

    // ---------- Global mapper via SqlPal.addTypeMapper ----------

    @Test fun `globally registered ValueMapper is consulted on read and write`() {
        // Registered for Money, a type used only by this test, so the process-wide
        // registration can't affect any other test (there is no public removal API).
        SqlPal.addTypeMapper(Money::class, MoneyMapper)

        val h = MoneyHolder(price = Money(1599))
        insert(h)
        // write went through the mapper → stored as a plain BIGINT
        assertEquals(1599L, readValue<Long>(-"SELECT price FROM money_holder WHERE id = ${h.id!!}"))
        // read went through the mapper → reconstructed Money
        assertEquals(Money(1599), selectById<MoneyHolder>(h.id!!).price)
    }

    // ---------- JSON collection storage ----------

    @Test fun `List of Int stored as JSON string when storeArraysAs=Json`() {
        SqlPal.storeArraysAs = ArrayStorageType.Json
        val list = JsonList(vals = listOf(1, 2, 3))
        insert(list)
        assertEquals("[1,2,3]", readValue<String>(-"SELECT vals FROM json_list WHERE id = ${list.id!!}"))
        assertEquals(listOf(1, 2, 3), selectById<JsonList>(list.id!!).vals)
    }

    @Test fun `empty List of Int stored as empty JSON array`() {
        SqlPal.storeArraysAs = ArrayStorageType.Json
        val list = JsonList(vals = emptyList())
        insert(list)
        assertEquals("[]", readValue<String>(-"SELECT vals FROM json_list WHERE id = ${list.id!!}"))
        assertEquals(emptyList(), selectById<JsonList>(list.id!!).vals)
    }
}
